/* TinniRelief Local Client Session Manager
   Local-only usage tracking. No cloud sync. No clinical inference.
*/
(function(){
'use strict';
const KEY='tinnirelief.clientSessions.v1';
const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {clients:Array.isArray(x.clients)?x.clients:[],sessions:Array.isArray(x.sessions)?x.sessions:[]}}catch{return{clients:[],sessions:[]}}};
let db=load(), active=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addNav(){const nav=document.querySelector('.bottom-nav');if(!nav||document.querySelector('[data-page="clients"]'))return;const b=document.createElement('button');b.className='nav-item';b.dataset.page='clients';b.innerHTML='◉<span>Clients</span>';nav.appendChild(b);}
function page(){let p=document.getElementById('clients');if(p)return p;p=document.createElement('section');p.id='clients';p.className='page';p.innerHTML='<div class="page-head"><div><p class="eyebrow">LOCAL CLIENT WORKSPACE</p><h1>Clients & Sessions</h1><p>Client codes, session duration and usage are stored on this device.</p></div></div><section class="card"><h2>Add client</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input id="crName" placeholder="Client code / initials"><input id="crNote" placeholder="Optional note"></div><button class="primary" id="crAdd" style="margin-top:10px">Add client</button></section><section class="card"><h2>Start client session</h2><select id="crClient"></select><select id="crType"><option value="Sound">Sound enrichment</option><option value="Program">Guided program</option><option value="Mixer">Sound mixer</option><option value="Check-in">Check-in</option></select><button class="primary" id="crStart" style="margin-top:10px">Start local session</button><div id="crActive" style="margin-top:10px"></div></section><section class="card"><h2>Session history</h2><div id="crStats"></div><div id="crList"></div><div style="display:flex;gap:8px;margin-top:10px"><button class="secondary" id="crExport">Export CSV</button><button class="secondary" id="crClear">Clear local records</button></div></section>';document.querySelector('main')?.appendChild(p);return p;}
function render(){const p=page(),sel=p.querySelector('#crClient');sel.innerHTML=db.clients.length?db.clients.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join(''):'<option value="">Add a client first</option>';const total=db.sessions.reduce((n,s)=>n+s.duration,0);p.querySelector('#crStats').innerHTML='<div style="display:flex;gap:18px;flex-wrap:wrap"><b>'+db.clients.length+' clients</b><b>'+db.sessions.length+' sessions</b><b>'+Math.round(total/60)+' min recorded</b><b>'+new Set(db.sessions.map(s=>s.day||String(s.startedAt).slice(0,10))).size+' active days</b></div>';p.querySelector('#crList').innerHTML=db.sessions.slice(0,30).map(s=>'<div style="padding:10px 0;border-bottom:1px solid var(--line)"><b>'+esc(s.clientName)+'</b> · '+esc(s.type)+' · '+Math.round(s.duration)+'s<br><small>'+new Date(s.startedAt).toLocaleString()+(s.program?' · '+esc(s.program):'')+'</small></div>').join('')||'<p>No sessions yet.</p>';p.querySelector('#crActive').innerHTML=active?'<b>Active:</b> '+esc(active.clientName)+' · '+esc(active.type)+' · '+Math.floor((Date.now()-active.startedMs)/1000)+'s <button class="secondary" id="crStop">Stop & save</button>':'No active session.';p.querySelector('#crAdd').onclick=()=>{const name=p.querySelector('#crName').value.trim();if(!name)return;db.clients.unshift({id:'C-'+Date.now(),name,note:p.querySelector('#crNote').value.trim(),createdAt:new Date().toISOString()});save();p.querySelector('#crName').value='';p.querySelector('#crNote').value='';render()};p.querySelector('#crStart').onclick=()=>{const c=db.clients.find(x=>x.id===sel.value);if(!c)return;active={clientId:c.id,clientName:c.name,type:p.querySelector('#crType').value,startedMs:Date.now(),startedAt:new Date().toISOString()};render()};p.querySelector('#crStop')?.addEventListener('click',()=>{if(!active)return;const end=Date.now();db.sessions.unshift({...active,endedAt:new Date(end).toISOString(),duration:(end-active.startedMs)/1000,program:null,day:new Date().toISOString().slice(0,10)});active=null;save();render()});p.querySelector('#crExport').onclick=()=>{const rows=[['client_id','client_name','type','started_at','ended_at','duration_sec'],...db.sessions.map(s=>[s.clientId,s.clientName,s.type,s.startedAt,s.endedAt,s.duration])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='tinnirelief-client-sessions.csv';a.click()};p.querySelector('#crClear').onclick=()=>{if(confirm('Delete all local client/session records on this device?')){db={clients:[],sessions:[]};active=null;save();render()}};}
document.addEventListener('click',e=>{const n=e.target.closest('[data-page="clients"]');if(n){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));page().classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})}});
document.addEventListener('click',e=>{const s=e.target.closest('[data-sound]');if(s&&active){active.type='Sound: '+(s.dataset.sound||'unknown')}}); 
document.addEventListener('DOMContentLoaded',()=>{addNav();page();});
})();
